TypeError: this.provider.getSigner is not a function
I'm providing an Ethers provider to SetJSConfig. However [this
line](https://github.com/SetProtocol/set.js/blob/master/src/wrappers/set-protocol-v2/ControllerWrapper.ts#L105)
assumes that `.getSigner()` is exposed on the provider. I don't think
this will be the case if we use an Alchemy / Infura provider. I thought
signers were only exposed if a user connect with a wallet.

Hmm, not sure how to expose a light read-only mode without access to
this method.